import Head from "next/head";
import styled from "styled-components";
import Homepage from "../components/homepage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MessageContainer>
        A setup for Next.js + Styled Component
      </MessageContainer>
      <Homepage />
    </div>
  );
}

const MessageContainer = styled.h1`
  color: lightgray;
  text-align: center;
`;
