import Head from "next/head";
import Header from "../components/Header";
import Homepage from "../components/homepage";
import { auth } from "../src/firebase/firebase.utils";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header />
      <Homepage />
    </div>
  );
}
